#
# 
#                                               
#                                               
#
# 
# id: mana
# or
# 'id:meta': mana
4: 0.5
87: 1
16: 2
15: 3
14: 4
56: 5
129: 6
153: 8
86: 8
103: 16
